# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[{
  goPackagePath = "gonum.org/v1/gonum";
  fetch = {
    type = "git";
    url = "https://github.com/gonum/gonum";
    rev = "ced62fe5104b907b6c16cb7e575c17b2e62ceddd";
    sha256 = "1b7q6haabnp53igpmvr6a2414yralhbrldixx4kbxxg1apy8jdjg";
  };
}]
